"""Realistic recombination scans on a biologically-shaped synthetic MSA.

The MSA is generated by :mod:`tests.factories` to mirror the real orthopoxvirus
example dataset (graded divergence, a large variola donor block, indels, a
fragmented multi-contig query) rather than uniform-random noise.
"""

from __future__ import annotations

import logging
from math import isnan
from pathlib import Path

from recomfi.recomb.analyze import analyze
from recomfi.recomb.regions import RegionParams, call_regions
from recomfi.recomb.run import RecombParams, run_recomb
from recomfi.recomb.similarity import compute_similarity

from ..conftest import write_fasta
from ..factories import make_recombination_msa

_LOG = logging.getLogger("recomfi.test")
WINDOW, STEP = 1000, 100


def _msa_path(records: dict[str, str], tmp_path: Path) -> Path:
    return write_fasta(tmp_path / "msa.fasta", records)


def _call(records: dict[str, str], tmp_path: Path):
    path = _msa_path(records, tmp_path)
    result = compute_similarity(str(path), "query", window_size=WINDOW, window_step=STEP)
    analysis = analyze(result)
    regions, major = call_regions(result, analysis, WINDOW, RegionParams.with_defaults(WINDOW))
    return result, analysis, regions, major


def test_major_parent_and_single_variola_region(tmp_path: Path) -> None:
    msa = make_recombination_msa(seed=1, length=20000)
    result, analysis, regions, major = _call(msa.records, tmp_path)

    # backbone is the major parent (query is closest to it genome-wide)
    assert major == msa.backbone == "cowpox_KC813504"
    # exactly one recombinant region, donor = variola, overlapping the donor block
    assert len(regions) == 1
    region = regions[0]
    assert region.minor_parent == "variola"
    assert region.major_parent == "cowpox_KC813504"
    d0, d1 = msa.donor_block
    assert region.msa_start <= d0 + WINDOW and region.msa_end >= d1 - WINDOW
    assert region.query_start < region.query_end


def test_graded_divergence_ranking(tmp_path: Path) -> None:
    msa = make_recombination_msa(seed=1, length=20000)
    _, analysis, _, _ = _call(msa.records, tmp_path)
    ranked = sorted(analysis.winners_with_ties.items(), key=lambda kv: kv[1], reverse=True)
    labels = [label for label, _ in ranked]
    # backbone wins the most windows; variola (the donor) is its main rival
    assert labels[0] == "cowpox_KC813504"
    assert "variola" in labels[:2]


def test_specificity_control_no_false_regions(tmp_path: Path) -> None:
    # A query that is pure backbone (no donor block) must call zero regions.
    msa = make_recombination_msa(seed=2, length=20000, recombinant=False)
    _, _, regions, major = _call(msa.records, tmp_path)
    assert major == "cowpox_KC813504"
    assert regions == []


def test_mixed_case_gives_identical_similarities(tmp_path: Path) -> None:
    # The real collection mixes lowercase and uppercase; case must not matter.
    upper = make_recombination_msa(seed=3, length=8000, uppercase=True)
    lower = make_recombination_msa(seed=3, length=8000, uppercase=False)
    up = compute_similarity(str(write_fasta(tmp_path / "u.fasta", upper.records)), "query",
                            window_size=WINDOW, window_step=STEP)
    lo = compute_similarity(str(write_fasta(tmp_path / "l.fasta", lower.records)), "query",
                            window_size=WINDOW, window_step=STEP)
    for label in up.similarities:
        for a, b in zip(up.similarities[label], lo.similarities[label], strict=True):
            assert (isnan(a) and isnan(b)) or a == b


def test_ambiguous_bases_are_uninformative(tmp_path: Path) -> None:
    # An N-run in the query yields uninformative (nan) windows, not 0.0, and
    # never inflates identity.
    msa = make_recombination_msa(seed=4, length=8000, recombinant=False,
                                 n_run=(2000, 1500))
    result, _, _, _ = _call(msa.records, tmp_path)
    # at least one window centred in the N-run is nan for every dataset
    nan_windows = [
        i for i, pos in enumerate(result.positions)
        if 2500 <= pos <= 3000
    ]
    assert nan_windows
    for i in nan_windows:
        assert all(isnan(result.similarities[ds][i]) for ds in result.similarities)


def test_multicontig_query_coordinates_lag_msa(tmp_path: Path) -> None:
    # A fragmented query (inter-contig gaps) makes query bases fewer than MSA
    # columns, so the query coordinate falls behind the MSA column past a gap.
    msa = make_recombination_msa(seed=5, length=20000, n_contigs=4, contig_gap=600)
    result = compute_similarity(str(_msa_path(msa.records, tmp_path)), "query",
                                window_size=WINDOW, window_step=STEP)
    # By the end of the alignment the query has lost ~3 * 600 bases to gaps.
    last_msa = result.positions[-1]
    last_query = result.query_positions[-1]
    assert last_query < last_msa
    assert last_msa - last_query >= 1500


def test_run_recomb_writes_report_and_regions(tmp_path: Path) -> None:
    msa = make_recombination_msa(seed=6, length=12000)
    path = _msa_path(msa.records, tmp_path)
    out = tmp_path / "out"
    run_recomb(
        RecombParams(msa=path, output=out, query="query", plot_format="png"), _LOG
    )
    regions = (out / "recombination_regions.tsv").read_text().splitlines()
    assert any("variola" in line for line in regions[1:])
    assert (out / "report.html").exists()
    assert "variola" in (out / "report.html").read_text()
